# 📊 Optimization Methods Assignment
## Asset Portfolio Optimization

### Group Members:
- Student 1: Chaya Kotuvila_MS25942316
- Student 2: Dilesha Wijayathilaka_MS25941876

### Module:
MSc Artificial Intelligence – Optimization Methods

---

## 🎯 Objective
This project aims to solve a real-world portfolio optimization problem using:
- Exact optimization method (SciPy SLSQP)
- Heuristic method (Genetic Algorithm)

We compare solution quality, runtime, and feasibility.

## 🧩 Problem Description

We aim to allocate capital across multiple financial assets to:

- Minimize portfolio risk (variance)
- Achieve a target return

This is a **resource allocation optimization problem**.

---

## 📊 Dataset

We use real-world financial data from Yahoo Finance:

Assets:
- Apple (AAPL)
- Microsoft (MSFT)
- Amazon (AMZN)
- Google (GOOGL)
- Tesla (TSLA)
- Netflix (NFLX)
- Bitcoin (BTC-USD)

Time Period: 2021–2026

Data is used to compute statistical properties (returns, covariance), not for training.

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from datetime import datetime
from scipy.optimize import minimize

In [ ]:
# =========================================================
# 1. Real-world Data Extraction (2021–2026)
# =========================================================

# Asset list
tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NFLX', 'BTC-USD']
data = yf.download(tickers, start="2021-01-01", end=datetime.now().strftime('%Y-%m-%d'))['Close']

# --- Before Cleaning ---
print(data.isnull().sum())
display(data.tail())

# --- Cleaning Process ---
# 1. Forward Fill
# 2. Dropna
data = data.ffill().dropna()

# --- After Cleaning ---
print(data.isnull().sum())
display(data.tail())

# --- Save ---
data.to_csv('portfolio_data_2026.csv')

/tmp/ipykernel_3503/1112553921.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start="2021-01-01", end=datetime.now().strftime('%Y-%m-%d'))['Close']
[*********************100%***********************]  7 of 7 completed

Ticker
AAPL       604
AMZN       604
BTC-USD      0
GOOGL      604
MSFT       604
NFLX       604
TSLA       604
dtype: int64

Ticker,AAPL,AMZN,BTC-USD,GOOGL,MSFT,NFLX,TSLA
Date,,,,,,,
2026-04-07,253.500000,213.770004,71940.703125,305.459991,372.290009,98.820000,346.649994
2026-04-08,258.899994,221.250000,71123.359375,317.320007,374.329987,99.389999,343.250000
2026-04-09,260.489990,233.649994,71767.828125,318.489990,373.070007,102.050003,345.619995
2026-04-10,260.480011,238.380005,72979.046875,317.239990,370.869995,103.010002,348.950012
2026-04-11,NaN,NaN,73054.273438,NaN,NaN,NaN,NaN

Ticker
AAPL       0
AMZN       0
BTC-USD    0
GOOGL      0
MSFT       0
NFLX       0
TSLA       0
dtype: int64

Ticker,AAPL,AMZN,BTC-USD,GOOGL,MSFT,NFLX,TSLA
Date,,,,,,,
2026-04-07,253.500000,213.770004,71940.703125,305.459991,372.290009,98.820000,346.649994
2026-04-08,258.899994,221.250000,71123.359375,317.320007,374.329987,99.389999,343.250000
2026-04-09,260.489990,233.649994,71767.828125,318.489990,373.070007,102.050003,345.619995
2026-04-10,260.480011,238.380005,72979.046875,317.239990,370.869995,103.010002,348.950012
2026-04-11,260.480011,238.380005,73054.273438,317.239990,370.869995,103.010002,348.950012